### ISSUE TITLE
Feature Request: Consider exporting CommonJS modules instead of ES6

### ISSUE THREAD

**Issue by mattcasey** [bangle-io/bangle.dev#153]
This is the only frontend library I have that is exporting ECMAScript modules. As a frontend library this means most consumers will need to have babel or something else to even use it. I've wasted 1-2 days now trying to get babel to work with my test runner, webpack, etc. It's still not perfect and has required a bunch of additional configuration on my end, so much I am tempted to just use ProseMirror directly. I don't mean to just complain; I'm willing to try and help add a build step if that helps.

**Comment by kepta** [comment]
Would it help if I provide some documentation and a complete webpack example that works with ESM ?

**Comment by kepta** [comment]
I have setup up demo repositories with different kinds of bundlers https://github.com/bangle-io/bangle.dev-boilerplates , including Webpack v4 so that setup is easier and is not painful as you mentioned.

I am going to close this ticket and I hope you give bangle.dev a try! Don't hesitate to reopen if you have any questions or thoughts.

**Comment by mattcasey** [comment]
Thanks, I'll check it out. If I still have issues I'll open another ticket with better examples
